config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  get 'search', to: 'stocks#search'
  resources :users, only: %i[index edit update]
  resources :customers do
    resources :products do
      collection { post :csv_import }
    end
  end
  resources :calendars do
    resources :stocks do
      collection { post :csv_import }
    end
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :calendar

  def self.csv_import(file, calendar)
    stocks = []
    CSV.foreach(file.path, headers: true) do |row|
      stock = Stock.new
      stock = find_by(id: row['id']) || new
      row_hash = row.to_hash.slice(*CSV_HEADER.keys)
      stock.attributes = row_hash.transform_keys(&CSV_HEADER.method(:[]))
      stock['calendar_id'] = calendar
      stocks << stock
    end
    Stock.import stocks
  end

  CSV_HEADER = {
    '書店コード' => 'store_code',
    '地区名' => 'district',
    '書店名' => 'store_name',
    '送品日付' => 'delivery_date',
    '陳列' => 'display',
    '雑誌コード' => 'magazine_code',
    '号数' => 'v1',
    '日付' => 'v2',
    '年' => 'v3',
    '出版社名' => 'publisher',
    '雑誌名' => 'magazine_name',
    '冊数' => 'num',
    '本体価格' => 'price',
    '特号' => 'special',
    '予約数' => 'reservation',
    '伝票番号' => 'slip',
    '商品コード' => 'product_code',
    '発行形態' => 'i_form',
    '判型' => 'format',
    '束数' => 'bundle',
    '端数' => 'fraction',
    'ISBNコード' => 'isbn',
    '買切雑誌' => 'purchased'
  }.freeze
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @calendar = Calendar.find(params[:calendar_id])
    @stocks = @calendar.stocks.where("num > ?",0).order("#{sort_column} #{sort_direction}").page(params[:page])
    @products = Product.all
  end

  def search
    @q = Stock.search(search_params)
    @stocks = @q.result.includes(:calendar).order("#{sort_column} #{sort_direction}").page(params[:page])
    @products = Product.all
  end

  def new
    @calendar = Calendar.find(params[:calendar_id])
  end

  def csv_import
    @calendar = Calendar.find(params[:calendar_id])
    Stock.csv_import(params[:file], params[:calendar_id])
    redirect_to root_path, notice: "#{l @calendar.day, format: :long}の入荷物を登録しました。"
  end

  private

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
    Stock.column_names.include?(params[:sort]) ? params[:sort] : 'id'
  end

  def search_params
    params.require(:q).permit!
  end

end

app/helpers/stocks_helper.rb
module StocksHelper
  def sort_order(column, title)
    css_class = (column == sort_column) ? "sort_current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == 'asc') ? 'desc' : 'asc'
    link_to title, { sort: column, direction: direction }, class: "sort_header #{css_class}"
  end
end

app/views/stocks/index.html.erb
<div class='stock-page'>
  <div class='stock-page__inner'>
    <div class='stock-page__inner--left stock-page__header'>
      <h2> Index Stock</h2>
      <h5><%= l @calendar.day, format: :long %>の入荷物一覧</h5>
      <div class=pagination>
      </div>
    </div>
    <div class='stock-page__inner--right'>
      <div class='stock-page__inner--right header'>
        <%= link_to "メイン画面に戻る", root_path, class: 'btn'%>
        <%= link_to "入荷日一覧画面へ", calendars_path , class: 'btn'%>
        <%= link_to "入荷日登録画面へ", new_calendar_path,class: 'btn' %>
      </div>
      <div class='stock-page__inner--right footer'>
        <%= link_to "入荷日変更画面へ", edit_calendar_path(@calendar.id),class: 'btn' %>
        <%= link_to "入荷物追加画面へ", new_calendar_stock_path(@calendar),class: 'btn' %>
        <%= link_to "入荷日削除画面へ", calendar_path(@calendar), method: :delete,class: 'btn' %>
      </div>
    </div>
  </div>
  <%= paginate(@stocks, :window => 2)%>
  <div class='stock-page__inner stock-page__footer'>
    <table>
      <thead>
        <tr>
          <th scope="col"><%= sort_order "display", "陳列" %></th>
          <th scope="col"><%= sort_order "publisher", "出版社名" %></th>
          <th scope="col"><%= sort_order "magazine_name", "雑誌名" %></th>
          <th scope="col"><%= sort_order "num", "冊数" %></th>
          <th scope="col"><%= sort_order "price", "本体価格" %></th>
          <th scope="col"><%= sort_order "i_form", "発行形態" %></th>
          <th scope="col"><%= sort_order "purchased", "買切雑誌" %></th>
          <th scope="col">予約数</th>
          <th scope="col">入荷日</th>
        </tr>
      </thead>
      <tbody>
        <% @stocks.each do |stock| %>
          <% num = 0 %>
          <% release = "" %>
          <% css_class = "" %>
          <% checks = Product.where(z_code: stock.magazine_code.to_i) %>
            <% if checks.present? %>
              <% (checks.to_a).each do |check| %>
                <% num += check.num %>
              <% end %>
              <% release = (checks.to_a)[0].release %>
              <% css_class = "color-red" %>
            <% end %>
              <tr class='<%= css_class%>' >
                <td><%= stock.display %></td>
                <td><%= stock.publisher %></td>
                <td><%= stock.magazine_name %></td>
                <td><%= stock.num %></td>
                <td><%= stock.price.to_s(:delimited) %></td>
                <td><%= stock.i_form %></td>
                <td><%= stock.purchased %></td>
                <td><%= num %></td>
                <td><%= release %></td>
              </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div id="pagetop">
  <a>ページトップ</a>
</div>

app/views/stocks/new.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Create Stock</h2>
      <h5><%= l @calendar.day, format: :long %>の入荷物登録</h5>
      <%= link_to "メイン画面に戻る", root_path, class: 'btn'%>
      <%= link_to "入荷日一覧画面へ", calendars_path, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with url: csv_import_calendar_stocks_path do |f| %>
        <div class='field'>
            <h3>日販のCSVファイルを入力してください</h3>
          <div class='field-label'>
            <%= f.label :入荷物%>
          </div>
          <div class='field-input'>
            <%= f.file_field :file, accept: '.csv' %>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "登録", class: 'btn'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/stocks/search.html.erb
<div class='stock-page'>
  <div class='stock-page__inner'>
    <div class='stock-page__inner--left stock-page__header'>
      <h2> Index Stock</h2>
      <h5>入荷物一覧</h5>
      <div class=pagination>
      </div>
    </div>
    <div class='stock-page__inner--right'>
      <div class='stock-page__inner--right header'>
        <%= link_to "メイン画面に戻る", root_path, class: 'btn'%>
        <%= link_to "入荷日一覧画面へ", calendars_path , class: 'btn'%>
        <%= link_to "入荷日登録画面へ", new_calendar_path,class: 'btn' %>
      </div>
      <div class='stock-page__inner--right footer'>
      </div>
    </div>
  </div>
  <%= paginate(@stocks, :window => 2)%>
  <div class='stock-page__inner stock-page__footer'>
    <table>
      <thead>
        <tr>
          <th scope="col"><%= sort_order "display", "陳列" %></th>
          <th scope="col"><%= sort_order "publisher", "出版社名" %></th>
          <th scope="col"><%= sort_order "magazine_name", "雑誌名" %></th>
          <th scope="col"><%= sort_order "num", "冊数" %></th>
          <th scope="col"><%= sort_order "price", "本体価格" %></th>
          <th scope="col"><%= sort_order "i_form", "発行形態" %></th>
          <th scope="col"><%= sort_order "purchased", "買切雑誌" %></th>
          <th scope="col">予約数</th>
          <th scope="col">入荷日</th>
        </tr>
      </thead>
      <tbody>
        <% @stocks.each do |stock| %>
          <% num = 0 %>
          <% release = "" %>
          <% css_class = "" %>
          <% checks = Product.where(z_code: stock.magazine_code.to_i) %>
            <% if checks.present? %>
              <% (checks.to_a).each do |check| %>
                <% num += check.num %>
              <% end %>
              <% release = (checks.to_a)[0].release %>
              <% css_class = "color-red" %>
            <% end %>
              <tr class='<%= css_class%>' >
                <td><%= stock.display %></td>
                <td><%= stock.publisher %></td>
                <td><%= stock.magazine_name %></td>
                <td><%= stock.num %></td>
                <td><%= stock.price.to_s(:delimited) %></td>
                <td><%= stock.i_form %></td>
                <td><%= stock.purchased %></td>
                <td><%= num %></td>
                <td><%= release %></td>
              </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div id="pagetop">
  <a>ページトップ</a>
</div>