config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  get 'search', to: 'stocks#search'
  resources :users, only: %i[index edit update]
  resources :customers do
    resources :products do
      collection { post :csv_import }
    end
  end
  resources :calendars do
    resources :stocks do
      collection { post :csv_import }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :name
    validates :code, format: { with: /\A\d{8}\z/, message: 'は半角数字8文字で入力してください' }
  end

  has_many :customers
  has_many :calendars
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @q = Stock.ransack(params[:q])
    @stocks = @q.result.includes(:calendar)
  end

  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :code, :email)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_main.html.erb
<div class="main1">
  <div class="main-search">
    <div class="form-input">
      <%= search_form_for @q, url: search_path do |f| %>
        <%= f.search_field :publisher_or_magazine_name_cont, class:"form-string", placeholder: "入荷物の検索を行います" %>
        <%= f.submit "検索", class:"form-submit" %>
      <% end %>
    </div>
  </div>
  <ul id="menu">
    <li><a href="#">お客様管理</a>
      <ul>
        <li>
          <%= link_to "お客様登録", new_customer_path %>
          <%# <a href="#">お客様登録</a> %>
        </li>
        <li>
          <%= link_to "お客様一覧", customers_path %>
        <%# <a href="#">お客様一覧</a> %>
        </li>
        <li><a href="#">お客様検索(未実装)</a></li>
      </ul>
    </li>
    <li><a href="#">入荷物管理</a>
      <ul>
        <li>
          <%= link_to "入荷物登録", new_calendar_path %>
        <%# <a href="#">入荷物登録</a> %>
        </li>
        <li>
          <%= link_to "入荷日一覧", calendars_path %>
        <%# <a href="#">入荷物一覧</a> %>
        </li>
        <li><a href="#">お客様印刷(未実装)</a></li>
      </ul>
    </li>
    <li><a href="#">コミック発注</a>
      <ul>
        <li><a href="#">新刊追加(未実装)</a></li>
        <li><a href="#">新刊補充(未実装)</a></li>
      </ul>
    </li>
    <li><a href="#">POP作成</a>
      <ul>
        <li><a href="#">明日入荷分(未実装)</a></li>
        <li><a href="#">明後日入荷分(未実装)</a></li>
        <li><a href="#">来月予約(未実装)</a></li>
      </ul>
    </li>
    <li><a href="#">予備</a>
      <ul>
        <li><a href="#">予備１</a></li>
        <li><a href="#">予備２</a></li>
        <li><a href="#">予備３</a></li>
      </ul>
    </li>
  </ul>
</div>

<div class="main2">
  <div class="sagyou-ue">
    <div class="koumoku">
      作業内容
    </div>
    <div class="jikan">
      作業終了日時
    </div>
  </div>
  <div class="sagyou-sita">
    <div class="naiyou">
      行った作業を一覧表示。(モデルに登録した時間で降順表示)文章をリンクにして内容紹介ページへリンク
    </div>
  </div>


  <div class="sagyou-ue">
    <div class="koumoku">
      例)お客様管理
    </div>
    <div class="jikan">
      2020/10/20(Tue) 17:13:48
    </div>
  </div>
  <div class="sagyou-sita">
    <div class="naiyou">
      ○○様の新規登録を行いました。
    </div>
  </div>

  <div class="sagyou-ue">
    <div class="koumoku">
      例)お客様管理
    </div>
    <div class="jikan">
      2020/10/20(Tue) 17:48:28
    </div>
  </div>
  <div class="sagyou-sita">
    <div class="naiyou">
      ○○様の編集を行いました。
    </div>
  </div>

  <div class="sagyou-ue">
    <div class="koumoku">
      例)お客様管理
    </div>
    <div class="jikan">
      2020/10/20(Tue) 17:48:28
    </div>
  </div>
  <div class="sagyou-sita">
    <div class="naiyou">
      ○○様の編集を行いました。
    </div>
  </div>

  <div class="sagyou-ue">
    <div class="koumoku">
      例)お客様管理
    </div>
    <div class="jikan">
      2020/10/20(Tue) 17:48:28
    </div>
  </div>
  <div class="sagyou-sita">
    <div class="naiyou">
      ○○様の編集を行いました。
    </div>
  </div>

  <div class="sagyou-ue">
    <div class="koumoku">
      例)お客様管理
    </div>
    <div class="jikan">
      2020/10/20(Tue) 17:48:28
    </div>
  </div>
  <div class="sagyou-sita">
    <div class="naiyou">
      ○○様の編集を行いました。
    </div>
  </div>

  <div class="sagyou-ue">
    <div class="koumoku">
      例)お客様管理
    </div>
    <div class="jikan">
      2020/10/20(Tue) 17:48:28
    </div>
  </div>
  <div class="sagyou-sita">
    <div class="naiyou">
      ○○様の編集を行いました。
    </div>
  </div>

  <div class="sagyou-ue">
    <div class="koumoku">
      例)お客様管理
    </div>
    <div class="jikan">
      2020/10/20(Tue) 17:48:28
    </div>
  </div>
  <div class="sagyou-sita">
    <div class="naiyou">
      ○○様の編集を行いました。
    </div>
  </div>

  <div class="sagyou-ue">
    <div class="koumoku">
      例)お客様管理
    </div>
    <div class="jikan">
      2020/10/20(Tue) 17:48:28
    </div>
  </div>
  <div class="sagyou-sita">
    <div class="naiyou">
      ○○様の編集を行いました。
    </div>
  </div>

  <div class="sagyou-ue">
    <div class="koumoku">
      例)お客様管理
    </div>
    <div class="jikan">
      2020/10/20(Tue) 17:48:28
    </div>
  </div>
  <div class="sagyou-sita">
    <div class="naiyou">
      ○○様の編集を行いました。
    </div>
  </div>
  <div class="sagyou-ue">
    <div class="koumoku">
      作業内容
    </div>
    <div class="jikan">
      作業終了日時
    </div>
  </div>

  <div class="sagyou-sita">
    <div class="naiyou">
      行った作業を一覧表示。(モデルに登録した時間で降順表示)文章をリンクにして内容紹介ページへリンク
    </div>
  </div>

  <div class="sagyou-ue">
    <div class="koumoku">
      例)お客様管理
    </div>
    <div class="jikan">
      2020/10/20(Tue) 17:13:48
    </div>
  </div>
  <div class="sagyou-sita">
    <div class="naiyou">
      ○○様の新規登録を行いました。
    </div>
  </div>

  <div class="sagyou-ue">
    <div class="koumoku">
      例)お客様管理
    </div>
    <div class="jikan">
      2020/10/20(Tue) 17:48:28
    </div>
  </div>
  <div class="sagyou-sita">
    <div class="naiyou">
      ○○様の編集を行いました。
    </div>
  </div>

</div>

app/views/users/_side_bar.html.erb
<div class="side1">
  <ul id="side-menu">
    <li>
      <%= link_to current_user.name, edit_user_path(current_user) %>
      <ul>
        <li>
          <a href="#">コミック要望表(未実装)</a>
        </li>
        <li>
          <a href="#">次月コミック登録未(未実装)</a>
        </li>
        <li>
          <a href="#">予備</a>
        </li>
        <li>
          <a href="#">月次業務登録(未実装)</a>
        </li>
      </ul>
    </li>
  </ul>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>登録店舗の編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "メイン画面に戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
      <%= render 'layouts/error_messages', model: f.object %>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :店舗名%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :店舗日販売ID%>
          </div>
          <div class='field-input'>
            <%= f.text_field :code%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :店舗email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="main">
    <%= render "main" %>
  </div>
</div>