config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  get 'search', to: 'stocks#search'
  resources :users, only: %i[index edit update]
  resources :customers do
    resources :products do
      collection { post :csv_import }
    end
  end
  resources :calendars do
    resources :stocks do
      collection { post :csv_import }
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :products, dependent: :destroy

  with_options presence: true do
    validates :name
    validates :name_kana, format: { with: /\A[ぁ-んー－]+\z/, message: 'は全角平仮名で入力してください' }
    validates :phone_number, numericality: { only_integer: true }, length: { maximum: 11 }
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all.order('created_at DESC')
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to root_path, notice: "#{@customer.name}様を登録しました。"
    else
      render :new
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to root_path, notice: "#{@customer.name}様を編集しました。"
    else
      render :edit
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    if @customer.destroy
      redirect_to root_path, notice: "#{@customer.name}様を削除しました。"
    else
      fursh.now[:aleat] = '削除に失敗しました。'
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :name_kana, :phone_number, :note1, :note2).merge(user_id: current_user.id)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Customer</h2>
      <h5><%=@customer.name%>様の情報を編集</h5>
      <%= link_to "取置商品登録画面", new_customer_product_path(@customer), class: 'btn'%>
      <br>
      <%= link_to "取置商品一覧画面", customer_products_path(@customer), class: 'btn'%>
      <br>
      <%= link_to "お客様一覧画面へ", customers_path, class: 'btn'%>
      <%= link_to "お客様情報を削除", customer_path(@customer.id), method: :delete, class: 'btn'%>
      <br>
      <%= link_to "メイン画面に戻る", root_path, class: 'btn'%>

    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: @customer, url: customer_path, local: true do |f|%>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :お客様名%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, placeholder:"例）山田太郎", autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :お客様名かな%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name_kana, placeholder:"例）やまだたろう"%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :電話番号%>
          </div>
          <div class='field-input'>
            <%= f.text_field :phone_number, placeholder:"例）09012345678",maxlength:"11"%>

          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :備考１『連絡時間などの注意事項を入力』%>
          </div>
          <div class='field-input'>
            <%= f.text_field :note1, placeholder:"（40文字まで)", maxlength:"40"%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :備考２『その他の注意事項を入力』%>
          </div>
          <div class='field-input'>
            <%= f.text_field :note2, placeholder:"（40文字まで)", maxlength:"40"%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "編集", class: 'btn'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/customers/index.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2> Index Customer</h2>
      <h5>お客様一覧</h5>

      <%= link_to "お客様登録画面へ", new_customer_path,class: 'btn' %>
      <%= link_to "メイン画面に戻る", root_path, class: 'btn'%>
    </div>
    <div class='account-page__inner--right'>
      <div >
        <ul>
          <% @customers.each do |customer| %>
            <li>
              <div class='customer_index_list'>
                <%= link_to edit_customer_path(customer.id), method: :get do %>
                  <div class='customer_index_list_header'>
                    <%= customer.name%> 様
                  </div>
                  <div class='customer_index_list_footer'>
                    <div class='customer_index_list_footer_left'>
                      電話番号:<%= customer.phone_number %>
                    </div>
                    <div class='customer_index_list_footer_right'>
                      登録日:<%= l customer.created_at %>
                    </div>
                  </div>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div id="pagetop">
  <a>ページトップ</a>
</div>

app/views/customers/new.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Create Customer</h2>
      <h5>新規お客様の登録</h5>
      <%= link_to "メイン画面に戻る", root_path, class: 'btn'%>
      <%= link_to "お客様一覧画面へ", customers_path, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: @customer, url: customers_path, local: true do |f|%>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :お客様名%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, placeholder:"例）山田太郎", autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :お客様名かな%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name_kana, placeholder:"例）やまだたろう"%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :電話番号%>
          </div>
          <div class='field-input'>
            <%= f.text_field :phone_number, placeholder:"例）09012345678",maxlength:"11"%>

          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :備考１『連絡時間などの注意事項を入力』%>
          </div>
          <div class='field-input'>
            <%= f.text_field :note1, placeholder:"（40文字まで)", maxlength:"40"%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :備考２『その他の注意事項を入力』%>
          </div>
          <div class='field-input'>
            <%= f.text_field :note2, placeholder:"（40文字まで)", maxlength:"40"%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "登録", class: 'btn'%>
        </div>
      </div>
    <% end %>
  </div>
</div>