config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  get 'search', to: 'stocks#search'
  resources :users, only: %i[index edit update]
  resources :customers do
    resources :products do
      collection { post :csv_import }
    end
  end
  resources :calendars do
    resources :stocks do
      collection { post :csv_import }
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :customer

  with_options presence: true do
    validates :z_code, numericality: { only_integer: true }, length: { maximum: 5 }
    validates :num, numericality: { only_integer: true }, length: { maximum: 5 }
    validates :release
  end

  def self.csv_import(file, customer)
    products = []
    CSV.foreach(file.path, encoding: 'Shift_JIS:UTF-8', headers: true) do |row|
      product = Product.new
      product = find_by(id: row['id']) || new
      row_hash = row.to_hash.slice(*CSV_HEADER.keys)
      product.attributes = row_hash.transform_keys(&CSV_HEADER.method(:[]))
      product['customer_id'] = customer
      products << product
    end
    Product.import products
  end

  CSV_HEADER = {
    '雑誌名' => 'name',
    '雑誌コード' => 'z_code',
    '取置冊数' => 'num',
    '発売日' => 'release'
  }.freeze
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @customer = Customer.find(params[:customer_id])
    @products = @customer.products.all.page(params[:page]).per(20).order('created_at DESC')
  end

  def new
    @customer = Customer.find(params[:customer_id])
    @product = Product.new
  end

  def create
    @customer = Customer.find(params[:customer_id])
    @product = @customer.products.new(product_params)
    if @product.save
      redirect_to edit_customer_path(@customer), notice: "#{@customer.name}様の取置商品を登録しました。"
    else
      render :new
    end
  end

  def edit
    @customer = Customer.find(params[:customer_id])
    @product = @customer.products.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:customer_id])
    @product = @customer.products.find(params[:id])
    if @product.update(product_params)
      redirect_to root_path, notice: "#{@customer.name}様の取置商品を編集しました。"
    else
      render :edit
    end
  end

  def csv_import
    @customer = Customer.find(params[:customer_id])
    Product.csv_import(params[:file], params[:customer_id])
    redirect_to root_path, notice: "#{@customer.name}様の取り置き商品を一括登録しました。"
  end

  private

  def product_params
    params.require(:product).permit(:name, :z_code, :num, :release).merge(customer_id: @customer.id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Product</h2>
      <h5><%=@customer.name%>様の取置商品編集</h5>
      <%= link_to "お客様取置一覧へ", customer_products_path(@customer), class: 'btn'%>
      <%= link_to "お客様一覧画面へ", customers_path, class: 'btn'%>
      <%= link_to "取置商品登録画面", new_customer_product_path(@customer), class: 'btn'%>
      <%= link_to "メイン画面に戻る", root_path, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: [@customer, @product], url: customer_product_path, local: true do |f|%>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :商品名%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, placeholder:"例）少年ジャンプ"%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :雑誌コード%>
          </div>
          <div class='field-input'>
            <%= f.text_field :z_code, placeholder:"例）29931", autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :取置冊数%>
          </div>
          <div class='field-input'>
            <%= f.text_field :num, placeholder:"例）1",maxlength:"11"%>

          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :発売日%>
          </div>
          <div class='field-input'>
            <%= f.text_field :release, placeholder:"例）月曜日", maxlength:"10"%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "登録", class: 'btn'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2> Index Products</h2>
      <h5><%=@customer.name%>様の取置商品一覧</h5>

      <%= link_to "お客様登録画面へ", new_customer_path,class: 'btn' %>
      <%= link_to "メイン画面に戻る", root_path, class: 'btn'%>
      <%= paginate(@products, :window => 2) %>
    </div>
    <div class='account-page__inner--right'>
      <div >
        <ul>
          <% @products.each do |product| %>
            <li>
              <div class='customer_index_list'>
                <%= link_to edit_customer_product_path(@customer, product.id), method: :get do %>
                  <div class='customer_index_list_header'>
                    定期 : <%= product.name%> 
                  </div>
                  <div class='customer_index_list_footer'>
                    <div class='customer_index_list_footer_left'>
                      取置冊数:<%= product.num %>
                    </div>
                    <div class='customer_index_list_footer_right'>
                      登録日:<%= l product.created_at %>
                    </div>
                  </div>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div id="pagetop">
  <a>ページトップ</a>
</div>

app/views/products/new.html.erb
<div class='product-page' id='product-page'>
  <div class='product-page__inner'>
    <div class='product-page__inner--left product-page__header'>
      <h2>Create Product</h2>
      <h5><%=@customer.name%>様の取置商品登録</h5>
      <%= link_to "お客様情報画面へ", edit_customer_path(@customer.id), class: 'btn'%>
      <%= link_to "お客様一覧画面へ", customers_path, class: 'btn'%>
      <br>
      <%= link_to "メイン画面に戻る", root_path, class: 'btn'%>
      <div class='product-page__inner--left product-page__footer'>
        <%= form_with url: csv_import_customer_products_path do |f| %>
          <div class='field'>
            <h6>一括登録用のCSVファイルがある場合はこちら</h6>
            <div class='field-label'>
              <%= f.label :取置商品リスト%>
            </div>
            <div class='field-input'>
              <%= f.file_field :file%>
            </div>
          </div>
          <div class='actions'>
            <%= f.submit "登録", class: 'btn'%>
          </div>
        <% end %>
      </div>
    </div>

    <div class='product-page__inner--right user-form'>
      <%= form_with model: [@customer, @product], url: customer_products_path, local: true do |f|%>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :商品名%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, placeholder:"例）少年ジャンプ"%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :雑誌コード%>
          </div>
          <div class='field-input'>
            <%= f.text_field :z_code, placeholder:"例）29931", autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :取置冊数%>
          </div>
          <div class='field-input'>
            <%= f.text_field :num, placeholder:"例）1",maxlength:"11"%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :発売日%>
          </div>
          <div class='field-input'>
            <%= f.text_field :release, placeholder:"例）月曜日", maxlength:"10"%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "登録", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>